Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	FilterDescriptions
	1

[Sat Apr 10 23:23:02 2021]
rule FilterDescriptions:
    input: data/gc-eu-descriptions.csv
    output: data/gc-list-eu-filtered.csv, figures/keyword-combinations-eu.png
    jobid: 0

[Sat Apr 10 23:23:06 2021]
Error in rule FilterDescriptions:
    jobid: 0
    output: data/gc-list-eu-filtered.csv, figures/keyword-combinations-eu.png

RuleException:
CalledProcessError in line 26 of /home/adrian/PhD-Laptop/Pd_Geocache/workflow/eu_snakefile:
Command 'set -euo pipefail;  Rscript --vanilla /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/scripts/tmp8vrrsxfi.filter_eu_descriptions.R' returned non-zero exit status 1.
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2189, in run_wrapper
  File "/home/adrian/PhD-Laptop/Pd_Geocache/workflow/eu_snakefile", line 26, in __rule_FilterDescriptions
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/home/adrian/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2201, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/log/2021-04-10T232302.550134.snakemake.log
